# Generated by Django 5.1.2 on 2024-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('widget_id', models.CharField(blank=True, max_length=255, null=True)),
                ('script', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LiveChat Settings',
                'verbose_name_plural': 'LiveChat Settings',
            },
        ),
    ]
